<a href="https://colab.research.google.com/github/AlexisCohen/Data-Sci/blob/main/Alexis_Cohen_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [38]:
for i in range(10):
    print(i)
#this is a for loop ot will run the code inside it in a loop depending on its range

0
1
2
3
4
5
6
7
8
9


In [39]:
for i in range(5,8):
    print(i)
#this loop ranges from 5-7

5
6
7


In [40]:
for i in range(3):
    print( "Test Number: " , i )

#This for loop prints both a string and the variable i

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [41]:
def square(x):
    return x**2

#this function squares whatever x is

In [42]:
square(5) #execution of the square function

25

In [43]:
square(square(2)) #execution of the square function inside a square function

16

In [44]:
square(square(square(2)))


256

In [45]:
square(123456) #execution of the square function

15241383936

In [46]:
square(square(5))  #execution of the square function inside a square function

625

In [47]:
def add_two(x):
    return x+2
#this function adds two to the variable x

In [48]:
add_two(5) #execution of the add two function

7

In [49]:
square(add_two(5)) #Using both the add two and square function to get a product

49

### Logical Branching

In [50]:
choice = "apple" #assigning the variable choie to the string apple

In [51]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

#This is an if statement that checks the variable choice if its apple and if 
#its true then it says "You choose apples." otherwise it says "You did not choose apples."

You choose apples.


In [52]:
choice = "orange" #choice is now "oranges"

In [53]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

#This is the same if else statement but now because choice is oranges 
#it results in "You did not choose apples."

You did not choose apples.


In [54]:
choice = "apple" #reassigning choice to "apple"

In [55]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123) 

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

# This is an if elif else statement which has options for if choice is apple or 
#orange and if neither is true then it also has an alternative result.

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [56]:
choice = input("Please enter your choice (i.e. apple): ")
#This allows for the user to input what the variable choice is assigned to

Please enter your choice (i.e. apple): apple


In [57]:
choice #this prints the new string that is assigned to choice

'apple'

In [58]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

#This is the same if elif else stamenet but now using the user input for choice

You choose apples.


#### Coins

In [59]:
import numpy as np

In [60]:
np.random.random() #prints a random number

0.22029936113274529

In [61]:
np.random.random() > 0.5 
#boolean that determines if the random number is above 0.5 or not

True

In [117]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

#If else statement that is dependant on whether or not the random number is above 0.5

In [63]:
flip_coin() 

#execution of the if else statment

Heads


### Graphics Output

In [64]:
from IPython.core.display import display, HTML

In [118]:
display(HTML('<h1>Hello, world!</h1>')) #how to make a string appear in heading format in a code box

In [66]:
def coin():
  return np.random.randint(2)

#this function makes coin be either 0 or 1

In [119]:
coin() #executing the function

0

In [68]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))
#how to display an image in a code box

In [69]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

#assigning an image to the variables heads and tails

In [124]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

#a function that will display the images assigned to variables

In [125]:
show_img(heads) #executing the show image function with the heads variable

In [126]:
show_img(tails)  #executing the show image function with the tails variable

In [127]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

#Depending on wether or not coin is 0 or 1 it will execute the show image function for the corresponding image

In [128]:
flip_coin() #execution of the flip coin function

In [129]:
for i in range(5):
    flip_coin()

# a for loop that repetes the flip coin function 5 times

In [130]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

#this is how you can have code and a heading in the same box
#this is the flip coin function rewriten 

### Cards

In [137]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

#This is a function changes the order of an array

In [138]:
a = np.arange(52)
# this array will be of 52 numbers long

In [139]:
shuffle(a) #the shuffle function shufles the values of the array labeled a

array([30, 40, 39, 35,  6, 31, 36, 48, 32, 20, 44,  2,  9, 49,  7, 34, 23,
       18, 14, 47, 15,  3, 22, 21, 45,  4, 13, 16,  1, 28,  0, 12, 43, 17,
       27, 24, 19, 50, 29, 46, 38,  5,  8, 51, 25, 10, 26, 42, 41, 37, 33,
       11])

In [141]:
np.random.permutation(52) #This is a random number generator with a range of 52

array([11, 35, 27, 40, 29, 39,  6, 36, 16,  5, 47, 13, 22, 10, 14,  0,  3,
       34, 19, 38, 30,  8, 31,  1, 17, 25, 46, 33, 41, 20, 23, 12, 51,  9,
       32, 48, 26, 21, 50, 37, 15, 49, 43, 44,  2, 28, 42,  4, 45,  7, 24,
       18])

### Speed Test

In [143]:
%%timeit
shuffle(a)
#this times how long the function takes

169 µs ± 818 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [82]:
%%timeit
np.random.permutation(52)
#this times how long the function takes

3.55 µs ± 235 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [83]:
import numpy as np

In [84]:
np.random.permutation(52) #This is a random number generator with a range of 52

array([20,  0, 44, 33, 38, 30,  8, 40, 46, 23,  9, 32, 35,  3, 42,  7, 47,
       49, 22,  2, 45, 24, 27, 11, 51, 41, 29, 25,  5, 26, 48, 21, 39, 34,
       28, 16, 50, 43,  1,  4, 37, 18, 31,  6, 19, 13, 36, 12, 10, 14, 15,
       17])

In [144]:
cards = np.random.permutation(52) 
#this assigns the variable cards to the array of random numbers with a range of 52

In [145]:
cards #the array assigned to cards printed

array([41,  0, 15, 42, 49, 50,  6, 31, 18, 11, 36, 27, 45, 21, 24, 38, 29,
       16, 23, 10, 44, 17, 43,  1,  3, 30, 25,  9, 19, 14, 20, 13, 48, 26,
       34, 46, 51,  8, 33, 35, 40, 28,  4, 32,  5,  7, 47, 12, 39,  2, 37,
       22])

In [150]:
cards[0] #This shows the first number on the cards array

41

In [88]:
cards[1] #This shows the second number on the cards array

14

In [151]:
cards[2] #This shows the third number on the cards array

15

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [152]:
np.arange(52).reshape(4,13)
#This puts the list in 4 rows and 13 colums to match the cards image

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [153]:
np.arange(52).reshape(4,13)%13
#this divides the numbers by 13 and leaves only the remeander

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [155]:
np.arange(52).reshape(4,13)//13
#This seperates the array after every 13 numbers

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [156]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']
#assigning arrays of strings that correspond to the number of cards as well as their suits

In [157]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

# the suits are given to each number changes after 13 numbers in the list 
#The card numbers are given based on the remander after they are divided by 13

In [158]:
card_name(0) 
#The first card in the array is an acce of clubs as assigned by the card_name function

'Ace of Clubs'

In [96]:
card_name(51)

'King of Diamonds'

In [97]:
cards = np.random.permutation(52)
#this assigns the variable cards to the array of random numbers with a range of 52

In [161]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])
#this makes the first in the list the top of the deck, and the same with the second and last

In [162]:
top_of_deck, second_card_in_deck, last_card_in_deck 
#what the card name is that is assigned to these variables

('Three of Diamonds', 'Ace of Clubs', 'Ten of Spades')

In [163]:
for i in range(5):
    print(card_name(cards[i]))

#this prints the names of the first five cards in the array

Three of Diamonds
Ace of Clubs
Three of Spades
Four of Diamonds
Jack of Diamonds


In [164]:
for i in range(15):
    print(card_name(cards[i]))

#this prints the names of the first 15 cards in the array

Three of Diamonds
Ace of Clubs
Three of Spades
Four of Diamonds
Jack of Diamonds
Queen of Diamonds
Seven of Clubs
Six of Hearts
Six of Spades
Queen of Clubs
Jack of Hearts
Two of Hearts
Seven of Diamonds
Nine of Spades
Queen of Spades


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [165]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"
#this assigns a url to the first variable and a string to the second variable

In [103]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']
#arrays assigned to the variables suit, and card

In [166]:
i = np.random.randint(4)
j = np.random.randint(13)
#this assigns a list to both variables that have a range of 4 and 13 

In [185]:
i,j #random results of the variables

(1, 3)

In [186]:
suit[i] #this will pick a random suit beacuse of the i variable

'p'

In [187]:
card[j] #this will pick a random card beacuse of the j variable

'4'

In [108]:
from IPython.core.display import display, HTML

In [183]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

#this is a show image function 

In [184]:
img = card_url_head + suit[i] + card[j] + card_url_tail
#this is a show image fuction that takes into account the card suit and number to get the correct card image from a website

In [188]:
show_img(img) #Executing show image the function

In [189]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

#This assigns a number to i and j depending on every 13 number and depending on the remander respectfully


In [192]:
card_image(3) #this is the functio card image being executed

'k4'

In [194]:
img = card_url_head + card_image(3) + card_url_tail 
#assigning the variable image to the function card image(3)

In [195]:
show_img(img)
#this is the proper image for the card assigned k4

In [197]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)
#this is the entire deck of cards with their corresponding images
#the function is in a for loop that has the range of 52 so it is able to cycle though every card once