<a href="https://colab.research.google.com/github/AlexisCohen/Data-Sci/blob/main/Lab_3_Cohen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Loops

In [1]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [2]:
for i in range(5,8):
  print(i)

5
6
7


In [6]:
for i in range(3):
  print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


#Functions

In [10]:
def square(x):
  return x**2

In [14]:
square(5) , square(4) # this is the function square repeated twice

(25, 16)

In [15]:
square(square(3)) # this is the function square being used on iteself which squares 3>9>81

81

In [16]:
square(12345678)

152415765279684

In [17]:
def addtwo(x):
  return x+2    #this creates a function that add two to whatever x is

In [18]:
addtwo(40)

42

In [19]:
choice = "apple"

In [29]:
if choice == "apple":
  print("You choose apples.")
else:
  print("You didn't choose apples.")

You choose apples.


In [37]:
if choice == "apple":
 
  print("You choose apples.")
  print("Thank you, shop again!")
 
elif choice == "orange":
 
    print("You choose oranges.")
    print("Thank you, shop again!")
 
else:
 
    print("You didn't choose apples or oranges.")
    print("Thank you, shop again!")

You choose oranges.
Thank you, shop again!


In [40]:
def ChoiceResponse(choice): 
  if choice == "apple":
  
    print("You choose apples.")
    print("Thank you, shop again!")
  
  elif choice == "orange":
  
      print("You choose oranges.")
      print("Thank you, shop again!")
  
  else:
  
      print("You didn't choose apples or oranges.")
      print("Thank you, shop again!")   #This is the choiccce if else statement but now it is a function

In [32]:
# Now Add User Input

In [74]:
choice = input("Please enter your choice (i.e. apple):")

ChoiceResponse(choice)

Please enter your choice (i.e. apple):orange
You choose oranges.
Thank you, shop again!


#AHHHHHHHHH

In [41]:
import numpy as np

In [46]:
cards = np.random.permutation(52)
cards

array([ 6,  1, 31,  4, 51, 36, 38, 12,  5, 39, 23,  9, 13, 49, 48,  2, 10,
        0,  7, 26, 11, 15, 42, 27, 21, 16, 29, 19, 47, 18, 24, 44, 40, 37,
       14, 20, 25, 41,  8,  3, 32, 33, 34, 46, 28, 17, 43, 50, 30, 45, 35,
       22])

In [45]:
cards[0]

37

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [47]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [48]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [49]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [50]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four', 'Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [80]:
def CardName(CardNumber):
    
    suit = CardNumber//13
    name = CardNumber%13

    return names[name] + " of " + suits[suit]

In [61]:
CardName(4)

'Five of Clubs'

In [63]:
cards = np.random.permutation(52)

In [64]:
TopDeck = CardName(cards[0])
SecondDeck = CardName(cards[1])
LastDeck = CardName(cards[-1])

In [66]:
TopDeck,SecondDeck,LastDeck

('Six of Hearts', 'Eight of Diamonds', 'Seven of Spades')

In [72]:
for i in range(5):
  print(CardName(cards[i]))

Six of Hearts
Eight of Diamonds
Three of Clubs
Ace of Diamonds
Four of Hearts


In [87]:
from IPython.core.display import display,HTML

In [83]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [84]:
i = np.random.randint(4)
j = np.random.randint(13)

In [85]:
suit[i]

'l'

In [86]:
card[j]

'q'

In [91]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [88]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [92]:
img = card_url_head + suit[i]+card[j] + card_url_tail

In [93]:
show_img(img)

In [95]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [96]:
card_image(3)

'k4'

In [97]:
img = card_url_head + card_image(3) + card_url_tail

In [98]:
show_img(img)

In [99]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)